version: '3.7'
services: 
    web:
        build: .
        ports:
        - "8080:8080"
        restart: always
        depends_on: 
            - database
        environment:
            PORT: 8080
            DATABASE_URL: "host=database port=5432 user=postgres dbname=postgres password=TokenTournamentSecretPW sslmode=disable"
    database:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: "TokenTournamentSecretPW"
