version: '3.7'
services: 
    web:
        build: .
        ports:
        - "8080:8080"
    database:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: "TokenTournamentSecretPW"
