version: '3.7'
services: 
    web:
        build: .
        ports:
        - "8080:8080"
        restart: always
        depends_on: 
            - database
    database:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: "TokenTournamentSecretPW"
